### ISSUE TITLE
[Feature Request] Copy Video URL to Clipboard

### ISSUE THREAD

**Issue by orithena** [albertogasparin/external-video-player-addon#2]

**Comment by orithena** [comment]
(Argh. Wrong button... here's the description)

Nice extension, it grabs the video URL alright from the page. But actually, I'd like to have the URL in my clipboard so I can paste it to my YouTuPi (see https://github.com/orithena/youtupi). No player that pops up as a choice on android offers me to copy the URL to clipboard... :(

Is there any chance to implement this?

**Comment by albertogasparin** [comment]
Sorry @orithena if I never replied, I lost the notification. Anyhow it is too late: Firefox 57+ killed my extension and I cannot make it work again for now (see #4). Going to close
