### ISSUE TITLE
Update to Firefox 57+

### ISSUE THREAD

**Issue by andres-conforti** [albertogasparin/external-video-player-addon#4]
Hey there, any news on an update for firefox quantum?

**Comment by albertogasparin** [comment]
Firefox 57+ [removed the API](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/HelperApps.jsm) I was using to trigger Android *intents* (the actual popup) and as of today there is no alternative solution.
I'm going to keep this issue open but looks like the new extensions platform is quite limited on Android and it is hard to predict if the functionality will be reintroduced in future versions.

**Comment by xawsi** [comment]
If it is not possible to trigger Android intents, is it maybe possible to copy the extracted video URI to the clipboard?
So it would be possible to open the URI in MX-Player (manually via the "Open Network Stream" command in MX-Player).
I have searched and experimented with many similar AddOns - but I didn't have any success for my use case. So I installed Firefox 56 APK to use external-video-player-addon again... :(

**Comment by Tuom** [comment]
It is possible to create intent by opening new tab with specific url. It is described in [this article](https://developer.chrome.com/multidevice/android/intents).
For example something like this:
"intent://" + url + "#Intent;action=android.intent.action.VIEW;scheme=http;type=video/*;end"

**Comment by albertogasparin** [comment]
@Tuom Amazing!! I never saw launching android intents that way. I knew about custom schemes for apps but ignored there is a generic `intent://`.
I have just published v2, fully compatible with Firefox 57+ on Android. 
Thanks and give it a go! 😉

**Comment by Tuom** [comment]
@albertogasparin I am glad, that I helped. Thanks, that you implement it so fast :+1:
