### ISSUE TITLE
Can't play vimeo or Youtube video

### ISSUE THREAD

**Issue by omar391** [albertogasparin/external-video-player-addon#5]
Please, check the youtube and Vimeo (as fas as I've tested) implementations. It cant play videos from these sites.

**Comment by albertogasparin** [comment]
Unfortunately Youtube, Vimeo, Netflix and several other video websites do not provide the video url in clear format. They instead use `blob` data for the html player, which cannot be used for viewing the stream elsewhere. 
Right now, developing a system to intercept the source of those streams is beyond the scope of this extension, sorry.
